# This file is expected to fail ❌ upon push until you fix the bug
# You successfully completed this level when this file pass 🟢 upon push
name: HACK - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for insecure actions
        run: | STATUS=$(curl -s https://www.githubstatus.com/api/v2/status.json | jq -r '.status.description') echo "GitHub Status: $STATUS"
